channels:
  - conda-forge
  - nodefaults
dependencies:
  - ipykernel
  # Dependencies for VS Code IDE
  - code-server>=3.2
  - jupyter-vscode-proxy
  - openssh
  - pre_commit
  # Remove once Pangeo has upstream.
  - virtualizarr>=2.0.0
  - icechunk
  # Working around https://github.com/holoviz/geoviews/pull/794
  - geoviews-core==1.14.1
  # Working around https://github.com/stac-utils/pystac/issues/1575
  - pystac==1.14.1
  - pip
  - pip:
    - git+https://github.com/MAAP-Project/stac_ipyleaflet.git@0.3.6
    - jupyter-sshd-proxy
    - jupyterlab-bxplorer
    - git+https://github.com/MAAP-Project/algorithms-jupyter-extension.git@feature/major-refactor
    - git+https://github.com/MAAP-Project/jupyter-server-extension.git@feature/major-refactor
    - git+https://github.com/MAAP-Project/maap-py.git@add-ogc-endpoints
variables:
  TITILER_STAC_ENDPOINT: 'https://openveda.cloud/api/stac'
  TITILER_ENDPOINT: 'https://openveda.cloud/api/raster'
  STAC_CATALOG_NAME: 'VEDA STAC'
  STAC_CATALOG_URL: 'https://openveda.cloud/api/stac'
  STAC_BROWSER_URL: 'https://openveda.cloud/'
  #MAAP_API_URL: 'https://api.uat.maap-project.org/'
  MAAP_PROFILE_URL: 'https://uat.maap-project.org/profile/'
